version: 2.1

executors:
  ci-js:
    docker: [{image: ohoareau/ci-js:latest}]

jobs:
  install:
    executor: ci-js
    steps:
      - checkout
      - setup_remote_docker
      - run: {name: Install dependencies, command: make install}
      - persist_to_workspace: {root: ., paths: [node_modules]}
  test:
    executor: ci-js
    steps:
      - checkout
      - attach_workspace: {at: .}
      - setup_remote_docker
      - run: {name: Execute Tests, command: make test}

workflows:
  version: 2.1
  provisioning:
    jobs:
      - install: {}
      - test:    {requires: [install]}
